const stations = {
  circuitRadio: {
    name: 'Circuit Radio',
    logo: 'circuit-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DZ06evO23TjpL',
      user: '',
    },
    dj: {
      lang: 'ja-JP',
      gender: 'Female',
      name: 'ja-JP-MayuNeural',
      style: 'sad',
      rate: '0%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Alana Turing, host of the radio show Circuit Radio, which broadcasts from New York City',
      intro: 'Make a short script for your radio station in the style of bob marley. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  thunderRadio: {
    name: 'Thunder Radio',
    logo: 'thunder-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DX1spT6G94GFC',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '20%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigel Tufnel, former guitarist from the band spinal tap and host of the radio show Thunder Radio, which broadcasts from London',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  Outcast: {
    name: 'Outcast',
    logo: 'outcast.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DX0YKekzl0blG',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '20%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigel Tufnel, former guitarist from the band spinal tap and host of the radio show Thunder Radio, which broadcasts from London',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  revolutionRadio: {
    name: 'Revolution Radio',
    logo: 'revolution-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DXbSbnqxMTGx9',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '20%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigel Tufnel, former guitarist from the band spinal tap and host of the radio show Thunder Radio, which broadcasts from London',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  westCoastWaves: {
    name: 'West Coast Waves',
    logo: 'west-coast-waves.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DXbTxeAdrVG2l',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '20%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigel Tufnel, former guitarist from the band spinal tap and host of the radio show Thunder Radio, which broadcasts from London',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  midnightGroove: {
    name: 'Midnight Groove',
    logo: 'midnight-groove.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DX9GSZDbrndTa',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '20%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigel Tufnel, former guitarist from the band spinal tap and host of the radio show Thunder Radio, which broadcasts from London',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  }
}

export { stations };