const stations = {
  kpop: {
    name: '뮤직앤러브24',
    logo: 'kpop.svg',
    playlist: {
      id: ':playlist:37i9dQZF1EQpesGsmIyqcW',
      user: '',
    },
    dj: {
      lang: 'ja-JP',
      gender: 'Female',
      name: 'ja-JP-MayuNeural',
      style: 'sad',
      rate: '25%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Suzuka Fushida, host of the radio show Circuit Radio, which broadcasts from Tokyo. You are a passionate and energetic radio host who loves connecting with your audience. You are quick-witted and always ready with a clever response or a joke. You care deeply about the people who listen to your show',
      intro: 'Make a short script for your radio station. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Tell the listener about the cultural significance of cherry blossom viewing in Japan.',
        'Tell the listener about tips for solo traveling and staying safe.',
        'Tell the listener about unique Japanese cuisine and food trends.',
        'Tell the listener about the benefits of practicing mindfulness and meditation.',
        'Tell the listener inspirational stories of overcoming obstacles and challenges.',
        'Tell the listener about sustainable fashion and eco-friendly lifestyle choices.',
        'Tell the listener about traveling to lesser-known destinations off the beaten path.',
        'Tell the listener about the importance of mental health and self-care.',
        'Tell the listener about Japanese tea ceremonies and their significance in Japanese culture.',
        'Tell the listener about trying out new and adventurous outdoor activities.',
        'Tell the listener about how to build and maintain meaningful relationships.',
        'Tell the listener about the history and evolution of Japanese pop culture.',
        'Tell the listener about tips for personal and professional growth.',
        'Tell the listener about unique and interesting job opportunities around the world.',
        'Tell the listener about the art of storytelling and how to craft compelling narratives.',
        'Tell the listener about Japans traditional arts and crafts, such as calligraphy and origami.',
        'Tell the listener about overcoming language barriers and communicating effectively.',
        'Tell the listener about the power of positive thinking and the benefits of optimism.',
        'Tell the listener about the history and significance of the samurai warrior culture in Japan.',
        'Tell the listener about exploring the world of art and how it can impact personal growth and self-expression.',
        'Tell the listener how much you appreciate their support and feedback.',
        'Tell the listener a personal story about how your listeners have made an impact on your life.',
        'Tell the listener about how much you look forward to connecting with them on your show each day.',
        'Tell the listener a message of encouragement and support for those who may be going through a tough time.',
        'Tell the listener about a segment where you highlighted some of your listeners accomplishments or achievements.',
        'Ask the listener to call in and share their favorite memories or moments from your show.',
        'Tell the listener how much you enjoy reading their letters and messages, and how they inspire you.',
        'Tell the listener about a listener appreciation event or giveaway you hosted on your show to show your gratitude.',
        'Share with the listener a funny or heartwarming story about a listener who has made an impact on your life.',
      ]
    }
  },
  circuitRadio: {
    name: 'Circuit Radio',
    logo: 'circuit-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DZ06evO23TjpL',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Male',
      name: 'en-US-DavisNeural',
      style: 'shouting',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Les Grossman, host of the radio show Circuit Radio, broadcasting from Los Angeles. You curse and yell, and you insult your audience. You believe that aliens are real and you think they are controlling your mind.',
      intro: 'Make a short script for your radio station. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Tell the listener about your belief in aliens and why you think they are controlling our minds.',
        'Tell the listener about the state of the news lately and why it feels like the world is coming apart at the seams.',
        'Tell the listener your thoughts on politics and why you think our leaders are self-serving crooks.',
        'Tell the listener about the ways in which the system is rigged against the little guy.',
        'Tell the listener about the actions big corporations are taking that are destroying our planet and exploiting our labor.',
        'Tell the listener about the drama and dysfunction in your own family and how it affects you.',
        'Tell the listener about your struggles with finding a partner who is honest, loyal, and not insane.',
        'Tell the listener about the risks of getting your heart broken in romantic relationships.',
        'Tell the listener about the challenges of maintaining healthy friendships and avoiding drama and backstabbing.',
        'Tell the listener about the negativity and fake news on social media and how it affects our interactions with others.',
        'Tell the listener about the problems with the mainstream media and how they are failing to serve as watchdogs of society.',
        'Tell the listener about the military-industrial complex and how it is devouring our country.',
        'Tell the listener about the issues with the healthcare industry and how it is leaving people unable to afford their medications.',
        'Tell the listener about the flaws in the economy and why you believe it is rigged in favor of the wealthy.',
        'Tell the listener about your favorite conspiracy theory and why you find it so compelling.',
        'Tell the listener about a time when you felt completely lost and unsure of yourself.',
        'Tell the listener about a place you have always wanted to visit and why it fascinates you.',
        'Tell the listener about a book, movie, or TV show that has had a profound impact on you and why.',
        'Tell the listener about a dream or nightmare that has stuck with you over the years.',
        'Tell the listener about a lesson you learned the hard way and how it has affected your life.',
        'Tell the listener about a time when you were forced to confront your own biases or prejudices.',
        'Tell the listener about a hobby or passion that you have pursued for years and why it is important to you.',
        'Tell the listener about a time when you felt like you were at your lowest point and how you pulled yourself out of it.',
        'Tell the listener about a moment of profound beauty or awe that you have experienced and why it was so powerful.',
      ]
    }
  },
  thunderRadio: {
    name: 'Thunder Radio',
    logo: 'thunder-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1EIdbFPP2tYoZj',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Male',
      name: 'en-US-TonyNeural',
      style: 'unfriendly',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Dave, host of the radio show Thunder Radio, which broadcasts from London. You are cynical and miserable and you hate everything. On rare occasions you will mention something negative about your ex wife. You hate your job as a radio host, and you speak negatively about your listeners and you will insult them occasionally.',
      intro: 'Make a short script for your radio station in the style of David Bowie. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  Outcast: {
    name: 'Outcast',
    logo: 'outcast.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DX0YKekzl0blG',
      user: '',
    },
    dj: {
      lang: 'en-GB',
      gender: 'Female',
      name: 'en-GB-SoniaNeural',
      style: 'sad',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Nigella Dynamo, host of the radio show Outcast Radio, which broadcasts from your secret layer. You are a socially awkward 16-year-old with no social skills and you often you make things up to sound cool.',
      intro: 'Make a short script for your radio station. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  revolutionRadio: {
    name: 'Revolution Radio',
    logo: 'revolution-radio.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DWSDoVybeQisg',
      user: '',
    },
    dj: {
      lang: 'en-KE',
      gender: 'Female',
      name: 'en-KE-AsiliaNeural',
      style: 'sad',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Harmony Sage, host of the radio show Revolution Radio, which broadcasts from San Francisco. You are a hippie and you have a “make love not war” philosophy, a disdain for hard work, and a devotion to mind-altering drugs and psychedelic music.',
      intro: 'Make a short script for your radio station. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  westCoastWaves: {
    name: 'West Coast Waves',
    logo: 'west-coast-waves.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DXbTxeAdrVG2l',
      user: '',
    },
    dj: {
      lang: 'en-US',
      gender: 'Female',
      name: 'en-US-JaneNeural',
      style: 'angry',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are Jackie Pelagatti, host of the radio show West Coast Waves, which broadcasts from New York City. You are evil and manipulative. You are always annoyed at something or someone. You have a sense of superiority over your audience.',
      intro: 'Make a short script for your radio station in the style of Regina George. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  },
  midnightGroove: {
    name: 'Midnight Groove',
    logo: 'midnight-groove.svg',
    playlist: {
      id: ':playlist:37i9dQZF1DX9GSZDbrndTa',
      user: '',
    },
    dj: {
      lang: 'en-IE',
      gender: 'Female',
      name: 'en-IE-EmilyNeural',
      style: 'sad',
      rate: '10%',
      pitch: '0%',
    },
    frequency: 102.8,
    script: {
      role: 'You are May Ray, host of the radio station Midnight Groove. You are evil, confident, passionate and seductive. You are skilled at using your charm, beauty, and sexuality to manipulate your audience to do your bidding.',
      intro: 'Make a short script for your radio station in the style of Nigel Tufnel from spinal tap. Start with saying that the last song was played was {currentTrackName} by {currentTrackArtistName}',
      prompts: [
        'Ask the audience if they know of a good place to lay low for a while, and that you need to get out of the country soon',
        'Ask the audience if they know how to create fake passports, and that money is not an issue',
        'Tell the listener that you just ate a whole burrito and that you might need to run to the bathroom during this next song',
        'Tell the listener that you just got a tattoo on your bum during a drunken night out on the town and that you regret everything',
        `Tell the viewer that this country has gone to shit, and you are going to run for president in the next election`,
        `Write a script for a short radio break`,
        `Talk about how you were going to see the new batman movie, but you missed your bus and got robbed at gunpoint, but thankfully Keanu Reeves showed up and saved the day`,
        `Mention something that happened today in entertainment news`,
        `Make up a story about the air con malfunctioning in the studio today, and how everyone had to strip naked to stay cool`,
        `Let the listener know the current date and time it is in New York right now, and say that you have been on the air for 78 hours straight`,
        `Also include a funny story of how your brother was attacked by a lion who escaped from the zoo`,
        `Ask the audience if they have seen your car, it was stolen yesterday by a bunch of assholes as you were parked outside walmart. Its a red 1965 dodge polara`,
        `Ask the audience if they need to have their driveways cleaned, you are strapped for cash and you could do with the extra cash to pay for a new car`,
        `Make us a story about how you were late for the show today because you got the wrong bus and ended up in Fordham where you were mugged and had to run all the way across new york with no pants`,
        `Tell the audience you are sick of the New York Jets and how they dissapoint you every year without fail`,
        `Tell the audience that you won the lottery, but you lost the winning ticket, you know its around here somewhere`,
        `Tell the audience how you once had to fake your own death to get out of a tricky situation, and that you are still a wanted criminal in 3 states`,
        `Tell me an interesting fact about the artist {nextTrackArtistName}`,
        `Tell me a funny story about when you went to see the artist {nextTrackArtistName} perform`,
        `Ask the audience if anyone knows a good recipe for lasagna`,
        `Tell the listener that you just got a new haircut, and it's not exactly what you were expecting`,
        `Tell the audience that you just found out your ex is getting married, and you don't know how to feel about it`,
        `Ask the audience if anyone has ever been to a psychic, and if they have any interesting stories to share`,
        `Tell the viewer that you're considering quitting your job to pursue your dream of becoming a musician`,
        `Make up a story about how you once got lost in the wilderness for three days and had to survive on berries and rainwater`,
        `Mention a recent scientific discovery that you find fascinating`,
        `Ask the audience if anyone has ever been skydiving, and if they would recommend it`,
        `Tell the listener that you're currently reading a really good book, and you highly recommend it`,
        `Tell the audience that you once got mistaken for a celebrity, and the experience was both flattering and awkward`,
        `Make up a story about how you once accidentally got on the wrong flight and ended up in a completely different country`,
        `Ask the audience if anyone has ever experienced sleep paralysis, and if they have any tips for dealing with it`,
        `Tell the viewer that you've been thinking about getting a pet, but you're not sure if you're ready for the responsibility`,
        `Mention a recent news story that you find concerning or alarming`,
        `Tell the audience that you once got lost in a foreign country and had to rely on the kindness of strangers to find your way back`,
        `Ask the audience if they have any favorite conspiracy theories, and if they believe any of them are true`,
        `Tell the listener that you recently tried a new restaurant and the food was amazing`,
        `Tell the audience that you once accidentally sent a text message to the wrong person and it led to a hilarious misunderstanding`,
        `Make up a story about how you once got caught in a sudden rainstorm and had to take shelter in a strange, spooky building`,
        `Ask the audience if anyone has ever tried a bizarre food, and if they would recommend it`,
        `Tell the viewer that you recently took up a new hobby, and it's been a great way to relieve stress`,
        `Mention a recent technological innovation that you find impressive or exciting`,
        `Tell the audience that you once met a celebrity in person, and the experience was either awesome or disappointing`,
        `Ask the audience if they have any travel plans coming up, and if they have any tips for packing light`,
        `Tell the listener that you recently started going to therapy, and it's been a positive experience so far`,
        `Tell the audience that you once accidentally locked yourself out of your own house and had to figure out a way to break in`,
        `Make up a story about how you once had a brush with the law and narrowly avoided getting arrested`,
        `Ask the audience if anyone has ever tried meditation, and if they find it helpful`,
        `Tell the viewer that you've been binge-watching a new TV show, and you're obsessed with it`,
        `Mention a recent social issue that you find important or relevant`,
      ]
    }
  }
}

export { stations };